// --- CHAT UI & API CONNECTION ---
const sendBtn = document.getElementById('send-button');
const userInput = document.getElementById('user-input');
const chatMessages = document.getElementById('chat-messages');

function addMessage(text, isBot = false) {
  const msgDiv = document.createElement('div');
  msgDiv.classList.add('message');
  msgDiv.classList.add(isBot ? 'bot-message' : 'user-message');
  msgDiv.innerHTML = text;
  chatMessages.appendChild(msgDiv);
  chatMessages.scrollTop = chatMessages.scrollHeight;
}

// --- VOICE RECOGNITION ---
let recognition = null;
const startRecBtn = document.getElementById('startRecBtn');
const stopRecBtn = document.getElementById('stopRecBtn');
const recordingIndicator = document.getElementById('recordingIndicator');

async function initSpeech() {
  try {
    const response = await fetch('/api/speech-config');
    const config = await response.json();

    if (!config.key || config.key === 'undefined') {
      console.warn('Azure Speech key not configured');
      return;
    }

    const speechConfig = SpeechSDK.SpeechConfig.fromSubscription(config.key, config.region);
    speechConfig.speechRecognitionLanguage = 'en-US';
    const audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
    recognition = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);

    recognition.recognized = (s, e) => {
      if (e.result.reason === SpeechSDK.ResultReason.RecognizedSpeech) {
        userInput.value += e.result.text + ' ';
      }
    };

    startRecBtn.onclick = () => {
      recognition.startContinuousRecognitionAsync();
      startRecBtn.style.display = 'none';
      stopRecBtn.style.display = 'inline-block';
      if (recordingIndicator) recordingIndicator.style.display = 'block';
    };

    stopRecBtn.onclick = () => {
      recognition.stopContinuousRecognitionAsync();
      stopRecBtn.style.display = 'none';
      startRecBtn.style.display = 'inline-block';
      if (recordingIndicator) recordingIndicator.style.display = 'none';
    };

  } catch (err) {
    console.warn('Speech init failed:', err.message);
  }
}

if (typeof SpeechSDK !== 'undefined') {
  initSpeech();
}

// --- FORMAT SOAP NOTE ---
function formatSOAP(data) {
  if (!data.subjective && !data.objective && !data.assessment && !data.plan) return '';

  return `
    <div class="soap-note">
      <h3>✅ Clinical Documentation Processed</h3>
      <div class="ai-disclaimer">
        ⚠️ AI-ASSISTED DRAFT: This note was generated by NurseIQ AI and must be reviewed and verified by a qualified nurse before use.
      </div>
      <p><strong>Patient:</strong> ${data.patientName || 'Unknown'}</p>
      <p><strong>S (Subjective):</strong> ${data.subjective || 'N/A'}</p>
      <p><strong>O (Objective):</strong> ${data.objective || 'N/A'}</p>
      <p><strong>A (Assessment):</strong> ${data.assessment || 'N/A'}</p>
      <p><strong>P (Plan):</strong> ${data.plan || 'N/A'}</p>
    </div>
  `;
}

// --- FORMAT MEDICATION SAFETY ---
function formatMedSafety(data) {
  const medData = data.medicationSafety || data;
  if (!medData || !medData.medications_detected || medData.medications_detected.length === 0) return '';

  const detected = medData.medications_detected.join(', ').toUpperCase();
  const severity = medData.severity_level || 'Low';
  const severityColor = severity === 'High' ? '🔴' : '🟢';

  let alertsHtml = '';
  if (medData.alerts && medData.alerts.length > 0) {
    alertsHtml = medData.alerts.map(alert => {
      const sev = alert.severity === 'High' ? '🔴' : '✅';
      let warningsHtml = '';
      if (alert.warning && typeof alert.warning === 'object') {
        warningsHtml = Object.entries(alert.warning).slice(0, 2).map(([key, val]) =>
          `<p><strong>${key}:</strong> ${String(val).substring(0, 150)}...</p>`
        ).join('');
      } else if (alert.warning) {
        warningsHtml = `<p>${String(alert.warning).substring(0, 200)}...</p>`;
      }
      return `
        <div class="med-alert">
          <strong>${sev} ${alert.medication.toUpperCase()}</strong> — Severity: ${alert.severity}
          ${warningsHtml ? `<div class="warnings">Warnings<br>${warningsHtml}</div>` : ''}
        </div>
      `;
    }).join('');
  } else {
    alertsHtml = '<p>✅ No drug interaction alerts found.</p>';
  }

  return `
    <div class="medication-safety">
      <h3>💊 Medication Safety Check</h3>
      <p>Detected: ${detected}</p>
      ${alertsHtml}
      <p><strong>Overall Severity: ${severityColor} ${severity}</strong></p>
    </div>
  `;
}

// --- FORMAT PATIENT COMMUNICATION ---
function formatPatientComms(data) {
  const comms = data.patientCommunication;
  if (!comms) return '';

  return `
    <div class="patient-communication">
      <h3>📋 Patient Discharge Summary</h3>
      ${comms.patientInstructions ? `
        <div class="comm-section">
          <strong>📝 Instructions:</strong>
          <p>${comms.patientInstructions}</p>
        </div>` : ''}
      ${comms.medications ? `
        <div class="comm-section">
          <strong>💊 Medications:</strong>
          <p>${comms.medications}</p>
        </div>` : ''}
      ${comms.warningSigns ? `
        <div class="comm-section warning-signs">
          <strong>⚠️ Warning Signs — Return to Hospital if:</strong>
          <p>${comms.warningSigns}</p>
        </div>` : ''}
      ${comms.followUp ? `
        <div class="comm-section">
          <strong>📅 Follow-up:</strong>
          <p>${comms.followUp}</p>
        </div>` : ''}
      ${comms.dietActivity ? `
        <div class="comm-section">
          <strong>🥗 Diet & Activity:</strong>
          <p>${comms.dietActivity}</p>
        </div>` : ''}
    </div>
  `;
}

// --- FORMAT COMPLIANCE AUDIT LOG ---
function formatComplianceAudit(data) {
  const audit = data.auditResult;
  if (!audit) return '';

  const statusColor = audit.complianceStatus === 'COMPLIANT' ? '🟢' : '🔴';
  const phiBadge = audit.containsPHI
    ? '<span style="background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:4px;font-size:0.85em;">⚠️ PHI Detected</span>'
    : '<span style="background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:4px;font-size:0.85em;">✅ No PHI</span>';

  let logsHtml = '';
  if (audit.auditEntries && audit.auditEntries.length > 0) {
    logsHtml = audit.auditEntries.map(entry => {
      const time = entry.timestamp ? entry.timestamp.split('T')[1]?.split('.')[0] : '';
      const action = entry.action || '';
      const details = entry.details || '';
      return `
        <div class="audit-entry">
          <span class="audit-time">${time}</span>
          <span class="audit-event">${action}</span>
          <span class="audit-detail"> — ${details}</span>
        </div>
      `;
    }).join('');
  }

  return `
    <div class="compliance-audit">
      <h3>🔒 Compliance & Audit Log</h3>
      <div class="compliance-header">
        <span>${statusColor} Status: <strong>${audit.complianceStatus || 'COMPLIANT'}</strong></span>
        &nbsp;&nbsp;${phiBadge}
        ${audit.agentsUsed ? `&nbsp;&nbsp;<span style="font-size:0.85em;color:#6b7280;">Agents: ${audit.agentsUsed.join(', ')}</span>` : ''}
      </div>
      <div class="audit-log">
        ${logsHtml || '<p style="color:#9ca3af;font-size:0.85em;">No audit entries</p>'}
      </div>
    </div>
  `;
}

// --- SEND NOTE & PROCESS ---
async function sendNote() {
  const noteText = userInput.value.trim();
  if (!noteText) return;

  addMessage(noteText, false);
  userInput.value = '';

  addMessage('<em>🔄 Processing with NurseIQ agents...</em>', true);

  try {
    const response = await fetch('/api/process-note', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ patientNote: noteText })
    });

    const data = await response.json();

    // Remove the loading message
    const messages = chatMessages.querySelectorAll('.bot-message');
    if (messages.length > 0) {
      messages[messages.length - 1].remove();
    }

    if (data.error) {
      addMessage(`❌ Error: ${data.error}`, true);
      return;
    }

    let outputHtml = '';
    outputHtml += formatSOAP(data);
    outputHtml += formatMedSafety(data);
    outputHtml += formatPatientComms(data);
    outputHtml += formatComplianceAudit(data);

    addMessage(outputHtml || '<p>⚠️ No output received from agents.</p>', true);

  } catch (err) {
    addMessage(`❌ Connection error: ${err.message}`, true);
  }
}

sendBtn.addEventListener('click', sendNote);
userInput.addEventListener('keypress', (e) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    sendNote();
  }
});